### ISSUE TITLE
java.sql.SQLFeatureNotSupportedException: isAutoIncrement()

### ISSUE THREAD

**Issue by gdegentile** [MonetDBSolutions/MonetDBe-Java#9]
Hi,

I recently did some additional testings.
Method MResultSetMetaData.isAutoIncrement() returns java.sql.SQLFeatureNotSupportedException: isAutoIncrement().

It makes more sense to return FALSE instead of returning an Exception saying that feature is not supported.

Regards,
Guillaume

**Comment by bernardom29** [comment]
Hi Guillaume,

Thanks for this input, this is fixed in the latest source version :)

Best regards,
Bernardo
